ENV_PATENT_APP_GCP_SQL_INSTANCE_CONN_NAME=jk-gcp-cert-project-303813:us-central1:patent-app-masterdata-db
ENV_PATENT_APP_GCP_SQL_INSTANCE_CONN_IP=34.69.37.185
ENV_PATENT_APP_GCP_SQL_INSTANCE_CONN_USER=root
ENV_PATENT_APP_GCP_SQL_INSTANCE_CONN_PASSWORD=MyFavDB$
GOOGLE_APPLICATION_CREDENTIALS=jk-gcp-cert-project-303813-2e28e814640d.json


# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';

# GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
